### ISSUE TITLE
Can't compile the ht16k33_alpha custom component

### ISSUE THREAD

**Issue by ShadyMCShadesen** [ssieb/custom_components#18]
I am not able to compile using the **ht16k33_alpha** custom component.

### **Logs:**
![esphome logs](https://bit.ly/341vmBf)

### **Config:**

```yaml
globals:
  - id: on_boot
    type: bool
    restore_value: false
    initial_value: 'true'

substitutions:
  # Device informations
  device_friendly_name: "HT16K33 Test"
  device_name: "ht16k33-test"
  device_entity_id: "ht16k33_test"
  # Pinout
  i2c_a_sda_pin: GPIO21
  i2c_a_scl_pin: GPIO22
  
# Device configuration
esphome:
  name: $device_name
  platform: esp32
# board: heltec_wifi_kit_32_v2   ###   i have a board with 8 MB flash so i tried using this one without success
  board: esp32dev
  on_boot:
    priority: -100
    then:
      - lambda: |-
          id(on_boot) = false;

# Import custom_components
external_components:
  - source:
      type: local
      path: custom_components
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $device_friendly_name
    password: !secret fallback_password

captive_portal:

web_server: # Could be disabled if performance issues appear
  port: 80
  auth:
    username: !secret esphome_web_username
    password: !secret esphome_web_password

# Set up I2C bus
i2c:
  - id: bus_a
    sda: $i2c_a_sda_pin
    scl: $i2c_a_scl_pin
    scan: true

# Set up display component
display:
  - platform: ht16k33_alpha
    address: 0x71
    scroll: true
    scroll_speed: 250ms
    scroll_dwell: 2s
    scroll_delay: 3
    lambda: |-
      it.print("Ht16K33 Display Test");
    id: ${device_entity_id}_display
```

**Board: [Mouser.com](https://eu.mouser.com/ProductDetail/Espressif-Systems/ESP32-DevKitC-VE?qs=sGAEpiMZZMv0NwlthflBi%252Br5FanRtbmfx%252BNQlezsXmY%3D&countrycode=DE&currencycode=EUR)**

**Display: [Mouser.com](https://eu.mouser.com/ProductDetail/Seeed-Studio/104020133?qs=sGAEpiMZZMv0NwlthflBi4vO7rZgU5LOSNDIFep7ods%3D&countrycode=DE&currencycode=EUR)**
