### ISSUE TITLE
`keypad` does not allow two buttons pressed at the same time

### ISSUE THREAD

**Issue by TheLastGimbus** [ssieb/custom_components#21]
Hi there!

I wanted to make a simple panel with few buttons to control my lighting. I have configured keypad like this:

```yaml
keypad:
  id: keypad1
  rows:
    - pin: D5
    - pin: D6
  columns:
    - pin: TX
    - pin: RX
    - pin: D1
  keys: "123456"
  has_diodes: false

binary_sensor:
  - platform: keypad
    keypad_id: keypad1
    id: btn_1
    name: button 1
    key: 1
  - platform: keypad
    keypad_id: keypad1
    id: btn_2
    name: button 2
    key: 2
  - platform: keypad
    keypad_id: keypad1
    id: btn_3
    name: button 3
    key: 3
  - platform: keypad ...
  ```

But this doesn't detect two buttons pressed at once! Only one :(

I also tried without "`keys`" (and `row` + `col` instead), but this doesn't work either...
