### ISSUE TITLE
Feature Request: Invert Desky up and down pins by default

### ISSUE THREAD

**Issue by OkhammahkO** [ssieb/custom_components#27]
The up and down pins need to be inverted for this component to function as expected, like I've done in the config excerpt below.

I think it could be nice for users if this was just somehow just done by default, or if there isn't a nice solution, you could also just add what I've got below to your config? 

Thank you

```
desky:
  id: my_desky
  up:    
    number: 4 #D2
    inverted: true 
  down:  
    number: 5 #D1
    inverted: true
  stopping_distance: 15  # optional distance from target to turn off moving, default 15  
```
