### ISSUE TITLE
Feature Request: Desky  - Stop movement 

### ISSUE THREAD

**Issue by OkhammahkO** [ssieb/custom_components#28]
It would be handy if desky component users had a way to stop the desk when it is in motion.

In my tests I just used a button which turned off both the up and the down pins (which need to be inverted;).

In my example below, you can also see how I've added interlocking (which we discussed may or may not be a good idea;)

You can also see I added a timeout of 15sec, which I thought might be a good idea to? 

Thank you!

```
button: 
#Stop movement 
  - platform: template
    name: Stop Desk
    id: desky_stop_desk
    on_press:
      then:
        - switch.turn_off: raise_desk
        - switch.turn_off: lower_desk
        

switch:
#wake up ther desk and request it sends its height 
  - platform: gpio
    id: wake_desk_and_get_height
    name: "Request Desk Height"
    pin:
      number: D5
      inverted: true
    on_turn_on:
    - delay: 100ms
    - switch.turn_off: wake_desk_and_get_height

#Raise the desk 
  - platform: gpio
    id: raise_desk
    name: "Raise Desk"
    pin:
      number: D2
      # mode: INPUT_PULLUP
      inverted: true
    interlock: lower_desk
    on_turn_on:
    #Auto off after 15s just in case
    - delay: 15s
    - switch.turn_off: raise_desk
#Lower the desk 
  - platform: gpio
    id: lower_desk
    name: "Lower Desk" 
    pin:
      number: D1
      # mode: INPUT_PULLUP
      inverted: true
    interlock: raise_desk
    on_turn_on:
   #Auto off after 15s just in case
    - delay: 15s
    - switch.turn_off: lower_desk    

```
