### ISSUE TITLE
Feature Request:  Add 'Is Moving'  and other 'current operation' sensors to desky

### ISSUE THREAD

**Issue by OkhammahkO** [ssieb/custom_components#29]
It would be handy if desky had some sensors telling you about it's current operation, much like Covers (e.g COVER_OPERATION_OPENING).

Perhaps DESKY_OPERATION_STATIONARY, DESKY_OPERATION_RAISING, and DESKY_OPERATION_LOWERING ? 

And perhaps a seperate binary sensor for whether it is moving or not? 

I have been testing with something similar to this for the latter , but I don't think it's a good implementation? 

Thank you! 

```
desky:
  id: my_desky
  up:    
    number: 4 #D2
    inverted: true 
  down:  
    number: 5 #D1
    inverted: true
  stopping_distance: 15  # optional distance from target to turn off moving, default 15  
  height:  # Sensor publishing the current height
    name: Desky Height
    id: desky_height
    internal: true
    filters:
    - delta: 0.05 #Only send values to HA if they change
    on_value:
      then:
          #Because of the delta filter, if the value changes, then the desk is moving (except on first value)
        - binary_sensor.template.publish:
            id: desky_is_moving
            state: ON
        - delay: 300ms
          #Assume it's stopped moving if no height changes after a short time.
        - binary_sensor.template.publish:
            id: desky_is_moving
            state: Off
          
binary_sensor:
  - platform: template
    id: desky_is_moving
    name: "Desky Is Moving"
    filters:
      - delayed_off: 400ms
    #If the desk isn't moving for a bit we better turn off attempts at movement. It's like poor man's collision detection? 
    on_release:
      then:
        - button.press: desky_stop_desk

```
