### ISSUE TITLE
Feature Request: Get Desky height on boot

### ISSUE THREAD

**Issue by OkhammahkO** [ssieb/custom_components#30]
Desky only sends height UART messages during and for a period after movement.

There is therefore no desk height data when your esp reboots.

But it seems there is a dedicated wire which can be used to request/activate the message stream (messages will then stop automatically after a few seconds and the desk will sleep again).

It would be handy if the Desky component requested height messages on boot so that users could see it's current (initial) height without having to move the desk.

Below is my test code in my config, which behaves as desired, however we discussed that this logic may be better either  located in your custom component files, and/or added to your provided config.

Thank you!

```

esphome:
  name: desky-d1mini-v2
  platform: ESP8266
  board: d1_mini #pinout: https://i0.wp.com/randomnerdtutorials.com/wp-content/uploads/2019/05/ESP8266-WeMos-D1-Mini-pinout-gpio-pin.png?quality=100&strip=all&ssl=1
  on_boot:
    priority: -100.0
    then:
    #Request a desk height update after boot.
      - delay: 5s
      - switch.turn_on: wake_desk_and_get_height

#later on...... (note the inversion)


switch:
#wake up ther desk and request it sends its height 
  - platform: gpio
    id: wake_desk_and_get_height
    name: "Request Desk Height"
    pin:
      number: D5
      inverted: true
    on_turn_on:
    - delay: 100ms
    - switch.turn_off: wake_desk_and_get_height

```
