### ISSUE TITLE
Feature Request: Desky | Support Height Decoder Variant

### ISSUE THREAD

**Issue by OkhammahkO** [ssieb/custom_components#40]
Pasted from our discord chat. Let me know if you need any more info.
----------------------------------------------------------
We’ve come across a desk which appears to be slightly different in one area.

In summary (and to refresh)...
Most desks send:
- This protocol over the RJ45 port. Bytes 3 and 4 (of 4) are used for height. We use this in your component.
https://discord.com/channels/429907082951524364/952464939480645642/957101799528095774
 - This protocol over the R12 port (for Bluetooth dongle port), and bytes 5 and 6 (of 9) are used for height. This is not used by the desky component. 
https://discord.com/channels/429907082951524364/952464939480645642/957107106492850246

But what we’ve found with some Jarvis desks is that they appear to actually send the second “9 byte message” over the RJ45 port. Everything else appears to be the same (including how the bytes are used to calculate height.
https://community.home-assistant.io/t/desky-standing-desk-esphome-works-with-desky-uplift-jiecang-assmann-others/383790/105?u=mahko_mahko
 
So I think the feature request is to be able to select/switch the protocol.
My thought was the revised config might look a bit like below? 

Thank you!

```
desky:
  #uart_id: desk_uart  (optional, unless multiple uarts are defined)
  id: my_desky
  height_protocol_variant: (optional, 4byte or 9byte, defaults to 4byte)
  height:  # optional sensor publishing the current height
    name: Desk Height
    # any other sensor options
 ```

**Comment by hraschan** [comment]
Hello @ssieb,

I stumbled across the HA project. I’m one of those users who would need this improvement. Would be amazing to add a second variant vor 9byte. I posted all my infos here:

https://community.home-assistant.io/t/desky-standing-desk-esphome-works-with-desky-uplift-jiecang-assmann-others/383790/296?u=hraschan

I will also look into your code. Maybe I’m able to implement it myself.

Greetings,
Max

**Comment by ssieb** [comment]
Any idea what the other bytes of the message are for?

**Comment by hraschan** [comment]
Not really. I actually really new to this topic. Maybe the display? My display is black when requesting the height. I only can confirm that 5 and 6 is necessary for calculating the heigh. At least for this desk.

**Comment by hraschan** [comment]
I looked into your code. Not really familiar with cpp. 

Are you combining byte 4 and 5 to calculate the height in the following part? 

` while (this->available()) {
    uint8_t c;
    int value;
    this->read_byte(&c);
    switch (state) {
     case 0:
      if (c == 1)
	state = 1;
      break;
     case 1:
      if (c == 1)
	state = 2;
      else
	state = 0;
      break;
     case 2:
      high_byte = c;
      state = 3;
      break;
     case 3:
      value = (high_byte << 8) + c;
      if (this->current_pos_ != value) {
        this->current_pos_ = value;
        if (this->height_sensor_ != nullptr)
          this->height_sensor_->publish_state(value);
      }
      state = 0;
      break;
    }
  }`

**Comment by OkhammahkO** [comment]
> Any idea what the other bytes of the message are for?

Similar to the most common protocol, I don''t think we ever decoded all bytes.

Interesting some controllers (like mine) appear to use the "common protocol" on the rj45  port and the "Other protocol" on the rj12 port.  On some controllers that rj12 port is for a bluetooth dongle.
But on other controllers they appear to just use the "other protocol" on the rj45  port.

https://community.home-assistant.io/t/desky-standing-desk-esphome-works-with-desky-uplift-jiecang-assmann-others/383790/23?u=mahko_mahko

**Comment by hraschan** [comment]
Is there an easy way to add the "Other protocol" config?

**Comment by OkhammahkO** [comment]
> Is there an easy way to add the "Other protocol" config? 

That's part of the suggested feature request... So not yet.

**Comment by ssieb** [comment]
ok, it should now auto-detect and use the correct protocol.

**Comment by OkhammahkO** [comment]
Auto detect!! Classic ssieb... Over achieving on the solution!😜

@hraschan can you please report back here and on the HA thread with how you go with testing? 

I might be able to help out a bit with minor config/hardware issues...

**Comment by hraschan** [comment]
Omg wow. Thats amazing. I will try that later and let you know.

**Comment by hraschan** [comment]
@ssieb I tried it at my desk. i get a value in home assistant. But its way off maybe the calculation is wrong?

<img width="350" alt="image" src="https://github.com/ssieb/esphome_components/assets/47531697/57a690f5-1763-499e-889e-a05b44213463">

```
[10:55:55][D][uart_debug:176]: <<< 242,242,1,3,**2,230**,15,251,126
[10:55:55][D][uart_debug:176]: <<< 242,242,1,3,**2,230**,15,251,126
`
2*256 +230 = 742mm

409.1mm in Home Assistant

**Comment by OkhammahkO** [comment]
Are you using just the basic config @hraschan ?

Best to start with that. 

Maybe share your config as next step. 

https://github.com/ssieb/esphome_components/blob/master/components%2Fdesky%2FREADME.md

**Comment by hraschan** [comment]
Yea 742 is the value my desk is showing.  

[10:55:55][D][uart_debug:176]: <<< 242,242,1,3,2,230,15,251,126
When calulating byte 7 and 8 then i get the value above:

15, 251

15*256 + 251 = 4091mm => 409.1cm

So the calculation is off. I'm using the config from [Mahko_Mahko](https://community.home-assistant.io/u/Mahko_Mahko)

**Comment by OkhammahkO** [comment]
Cool let's see what ssieb reckons.

**Comment by hraschan** [comment]
Ohhh hahah. Sorry man. I didn't read your name correctly. If @ssieb is requesting his config I can try any time.

**Comment by hraschan** [comment]
Thanks tho 😍 I will try tomorrow.

**Comment by hraschan** [comment]
Thank you @ssieb and @OkhammahkO it works like a charm. You can close this issue. I will also comment in the HA Thread.

**Comment by jcastro** [comment]
I'm also going to give it a try just need to get the latest config setup! thank you all

**Comment by jcastro** [comment]
@ssieb @hraschan I think everything is working perfectly, except for the height sensor, which sometimes shows the correct value but sometimes shows very random numbers (even out of range of what the desk is capable of moving). If you want, let me know how I can help with debugging this! (using the same config as @hraschan, but with an ESP8266)

<img width="581" alt="image" src="https://github.com/ssieb/esphome_components/assets/190036/83dc4ba5-e23e-4dfd-9997-6173897cb292">

**Comment by ssieb** [comment]
I found a detailed description of the "9" byte protocol, so it looks like I can add checksum verification and also check that it's receiving the correct message type.  For now, if you can see in the uart debug log what happens with the bad values, that would be helpful.

**Comment by jcastro** [comment]
Absolutely, let me know [if this video helps.](https://d.pr/v/6PczBB+)

Memory 1 is 70.1 cm (as shown on the screen)
Memory 2 is 103 cm (as shown on the screen)

**Comment by ssieb** [comment]
That video shows that you're losing data, probably because of software serial on the 8266.
I've added message verification, so try it now.  You should get warnings in the log instead of bad data.

**Comment by jcastro** [comment]
looks like now it's working a bit better, at least showing sometimes the right height. I can swap the 8266 for an ESP32 tomorrow (actually, it's the latest 8266 I have at home haha)

[New video here](https://d.pr/v/ayoDmT+)

**Comment by ssieb** [comment]
@jcastro why is it getting the 4 byte protocol now?  And what is that "request desk height" switch?

**Comment by jcastro** [comment]
I have no idea tbh! but here's my config (from @hraschan)

```
esphome:
  name: standing-desk
  friendly_name: Standing Desk
  on_boot:
    priority: -100.0
    then:
    #Request a desk height update after boot.
      - delay: 5s
      - switch.turn_on: wake_desk_and_get_height
esp8266:
  board: d1_mini

# Enable logging
logger:
  #level: VERY_VERBOSE
  # baud_rate: 0 #disable logging over uart
# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.0.10.57

external_components:
#Fetch ssieb's custom component# https://github.com/ssieb/custom_components/tree/master/components/desky
  - source:
      type: git
      url: https://github.com/ssieb/custom_components
    components: [ desky ]

uart:
  - id: desk_uart
    baud_rate: 9600
    rx_pin: TX
    ##You can uncomment the debug section below to see UART messages.
    debug:
      dummy_receiver: true
      after:
        bytes: 9
      sequence:     
        - lambda: UARTDebug::log_int(direction, bytes, ',');
 
desky:
  id: my_desky
  ####################################################################################
  ##Uncomment this block to use Ssieb's move_to componet function.
  # up:    
    # number: 4 #D2
    # inverted: true 
  # down:  
    # number: 5 #D1
    # inverted: true
  # stopping_distance: 15  # optional distance from target to turn off moving, default 15  
  ####################################################################################
  height:  # Sensor publishing the current height
    name: Desky Height
    id: desky_height
    accuracy_decimals: 1
    unit_of_measurement: cm
    #any other sensor options
    filters:
    - delta: 0.05 #Only send values to HA if they change
    - throttle: 200ms #Limit values sent to Ha to 5 per sec.
    - multiply: 0.1 #convert from mm to cm
    on_value:
      then:
          #If the value changes, then the desk is moving
        - binary_sensor.template.publish:
            id: desky_is_moving
            state: ON
        - delay: 300ms
          #Assume it's stopped moving if no height changes after a short time.
        - binary_sensor.template.publish:
            id: desky_is_moving
            state: Off
            
binary_sensor:
  - platform: template
    id: desky_is_moving
    name: "Desky Is Moving"
    filters:
      - delayed_off: 400ms
    #If the desk isn't moving for a bit we better turn off attempts at movement. It's like poor man's collision detection? 
    on_release:
      then:
        - button.press: desky_stop_desk
substitutions:
  #Use your own ESP pin values
  desky_request_height_pin: D5 #Request desk height | white wire  
  desky_purple_pin: D6 #purple wire  
  desky_down_pin: D1 #Move desk down | yellow wire  
  desky_up_pin: D2  #Move desk up | green wire  

output:
  - platform: gpio
    pin: ${desky_up_pin}
    id: up_green_wire
    inverted: true
  - platform: gpio
    pin: ${desky_down_pin}
    id: down_yellow_wire
    inverted: true
  - platform: gpio
    pin: ${desky_purple_pin}
    id: purple_wire
    inverted: true

switch:
#wake up ther desk and request it sends its height 
  - platform: gpio
    id: wake_desk_and_get_height
    name: "Request Desk Height"
    pin:
      number: ${desky_request_height_pin}
      inverted: true
    on_turn_on:
    - delay: 100ms
    - switch.turn_off: wake_desk_and_get_height

#Raise the desk 
  - platform: output
    output: up_green_wire
    id: raise_desk
    name: "Raise Desk"    
    on_turn_on:
    #Auto off after 15s just in case
    - delay: 15s
    - switch.turn_off: raise_desk
#Lower the desk 
  - platform: output
    output: down_yellow_wire
    id: lower_desk
    name: "Lower Desk" 
    on_turn_on:
   #Auto off after 15s just in case
    - delay: 15s
    - switch.turn_off: lower_desk

button:
  # Combination Buttons
  - platform: template
    name: "Memory 1"
    id: button_1
    on_press:
      then:
        - output.turn_on: up_green_wire
        - output.turn_on: down_yellow_wire
        - delay: 300ms
        - output.turn_off: down_yellow_wire
        - output.turn_off: up_green_wire
  - platform: output
    output: purple_wire
    name: "Memory 2"
    id: button_2
    duration: 300ms
  - platform: template
    name: "Memory 3"
    id: button_3
    on_press:
      then:
        - output.turn_on: purple_wire
        - output.turn_on: down_yellow_wire
        - delay: 300ms
        - output.turn_off: down_yellow_wire
        - output.turn_off: purple_wire
  - platform: template
    name: "Memory 4"
    id: button_4
    on_press:
      then:
        - output.turn_on: purple_wire
        - output.turn_on: up_green_wire
        - delay: 300ms
        - output.turn_off: up_green_wire
        - output.turn_off: purple_wire
#Stop movement 
  - platform: template
    name: Stop Desk
    id: desky_stop_desk
    on_press:
      then:
        - switch.turn_off: raise_desk
        - switch.turn_off: lower_desk
```

**Comment by hraschan** [comment]
Maybe your 8266 is falty. You should also try the esp32

**Comment by OkhammahkO** [comment]
> I found a detailed description of the "9" byte protocol, so it looks like I can add checksum verification and also check that it's receiving the correct message type.  For now, if you can see in the uart debug log what happens with the bad values, that would be helpful.

I'm curious about this protocol. Do you have a link?

**Comment by OkhammahkO** [comment]
@jcastro consider using a basic config for debugging so that ssieb doesn't have to navigate all the details of a more complex setup.

https://github.com/ssieb/esphome_components/blob/master/components%2Fdesky%2FREADME.md

Per my advice under software heading here. 

https://community.home-assistant.io/t/desky-standing-desk-esphome-works-with-desky-uplift-jiecang-assmann-others/383790/18?u=mahko_mahko

**Comment by OkhammahkO** [comment]
> @jcastro why is it getting the 4 byte protocol now?  And what is that "request desk height" switch?

I wonder if the controller might switch protocol depending on the outcome of a handset startup sequence?

The Phord project gives some hint about this. 

https://github.com/phord/Jarvis

**Comment by ssieb** [comment]
> There's some more info about the protocol from another project here.
> https://github.com/phord/Jarvis

That's the one I was referring to.

> I wonder if the controller might switch protocol depending on the outcome of a handset startup sequence?

I thought this was intercepting the display interface, so there's no handset involved.

> It also mentions the messages for the 9 byte protocol it can be [between 6 and 9 bytes](https://github.com/phord/Jarvis#uart-protocol).

Yes, that's why I'm also checking the message type in case something else shows up.

**Comment by jcastro** [comment]
@OkhammahkO @ssieb I've switched to a simple configuration (pasting it below) on an ESP32-S3 and it seems to work fine, except for the desk moving sensor

This video shows me changing the height on the desk controller and then tapping on the Memory 1 button
https://github.com/ssieb/esphome_components/assets/190036/2a8d5820-345a-475c-8d5c-3c22716c2778

Current config
```
esphome:
  name: standing-desk
  friendly_name: Standing Desk

esp32:
  board: esp32-s3-devkitc-1

external_components:
  # Fetch ssieb's custom component: https://github.com/ssieb/custom_components/tree/master/components/desky
  - source:
      type: git
      url: https://github.com/ssieb/custom_components
    components: [ desky ]

# Enable logging
logger:
  #level: VERY_VERBOSE
  # baud_rate: 0 # disable logging over uart

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.0.10.26

uart:
  - id: desk_uart
    baud_rate: 9600
    rx_pin: GPIO16

desky:
  id: my_desky
  height:  # optional sensor publishing the current height
    name: Desk Height
  up:    # optional <pin> config
    number: GPIO18
    inverted: true  # probably needed
  down:  # optional <pin> config
    number: GPIO21  # Corrected pin number
    inverted: true  # probably needed
  request:  # optional <pin> config to request height updates at boot
    number: GPIO17
    inverted: true  # probably needed
  stopping_distance: 65  # optional distance from target to turn off moving, default 15
  timeout: 15s  # optional time limit for moving, default is none

binary_sensor:
  - platform: template
    name: Desky moving
    lambda: return id(my_desky).current_operation != desky::DESKY_OPERATION_IDLE;
```
