### ISSUE TITLE
Growatt - not expected output

### ISSUE THREAD

**Issue by sanderlv** [ssieb/custom_components#8]
Have tried https://github.com/ssieb/custom_components/tree/master/growatt

This esphome:
```
esphome:
  name: growatt_modbus
  platform: ESP8266
  board: d1_mini

substitutions:
  esp_name: growatt_modbus

wifi:
  ssid: "IOTDOM"
  password: !secret IOTDOM_wifi_key
  use_address: 192.168.6.42
  domain: .local.local
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esp_name} fb Hotspot"
    password: !secret Fallback_Hotspot

captive_portal:

# Enable logging
logger:
  level: VERBOSE
#  baud_rate: 9600

# Enable Home Assistant API
api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time

uart:
  tx_pin: D1
  rx_pin: D2
  baud_rate: 9600
  # stop_bits: 2

sensor:
  - platform: wifi_signal
    name: "${esp_name} - WiFi Signal"
    update_interval: 6s
    
  - platform: uptime
    name: "${esp_name} - Uptime"
    icon: mdi:clock-outline
    update_interval: 60s
    
  - platform: growatt
    id: my_growatt
    input_power:
      id: input_power
      name: "${esp_name} Input Power"
    pv1_voltage:
      id: pv1_voltage
      name: "${esp_name} PV1 Voltage"
    pv1_current:
      id: pv1_current
      name: "${esp_name} PV1 Current"
    pv1_power:
      id: pv1_power
      name: "${esp_name} PV1 Power"
    pv2_voltage:
      id: pv2_voltage
      name: "${esp_name} PV2 Voltage"
    pv2_current:
      id: pv2_current
      name: "${esp_name} PV2 Current"
    pv2_power:
      id: pv2_power
      name: "${esp_name} PV2 Power"
    grid_frequency:
      id: grid_frequency
      name: "${esp_name} Grid Frequency"
    output_power:
      id: output_power
      name: "${esp_name} Output Power"
    temperature:
      id: temperature
      name: "${esp_name} Temperature"

# https://github.com/ssieb/custom_components/tree/master/growatt
```

Gives this output:
![image](https://user-images.githubusercontent.com/16528916/101777130-50619080-3af2-11eb-99eb-3002e6b4db79.png)
