### ISSUE TITLE
cam compiling error

### ISSUE THREAD

**Issue by cyrok** [ssieb/custom_components#88]
i struggle while compiling. i checked multiple times but cant figure out, what im doing wrong.
here my yaml and the output log.

```
# Basic configuration for an ESP32 device
esphome:
 name: cam1
 friendly_name: Kamera Küchenfenster

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/MichaKersloot/esphome_custom_components
    components: [ esp32_camera ]

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXX"

ota:
  - platform: esphome
    password: "XXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cam1 Fallback Hotspot"
    password: "XXX"

esp32_camera_web_server:
  - port: 21001
    mode: stream
  - port: 21011
    mode: snapshot

esp32_camera:
  external_clock:
    pin: GPIO15
    frequency: 15MHz
  i2c_pins:
    sda: GPIO4
    scl: GPIO5
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13
  resolution: 2560x1920
  jpeg_quality: 10
  name: cam1
```

```
INFO ESPHome 2025.6.0
INFO Reading configuration /config/cam.yaml...
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.8.2
INFO Updating https://github.com/espressif/esp32-camera.git@v2.0.15
INFO Compiling app...
Processing cam (board: esp32-s3-devkitc-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip)
--------------------------------------------------------------------------------
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - framework-espidf @ 3.50302.0 (5.3.2) 
 - tool-cmake @ 3.30.2 
 - tool-esptoolpy @ 4.8.6 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 14.2.0+20240403 
 - tool-xtensa-esp-elf-gdb @ 14.2.0+20240403 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 13.2.0+20240530 
 - toolchain-xtensa-esp-elf @ 13.2.0+20240530
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.6
Compiling .pioenvs/cam/src/esphome/components/esp32_camera/esp32_camera.cpp.o
Archiving .pioenvs/cam/esp-idf/esp_http_client/libesp_http_client.a
Compiling .pioenvs/cam/esp_http_server/src/httpd_parse.c.o
Compiling .pioenvs/cam/esp_http_server/src/httpd_sess.c.o
Compiling .pioenvs/cam/esp_http_server/src/httpd_txrx.c.o
Compiling .pioenvs/cam/esp_http_server/src/httpd_uri.c.o
Compiling .pioenvs/cam/esp_http_server/src/httpd_ws.c.o
Compiling .pioenvs/cam/esp_http_server/src/util/ctrl_sock.c.o
Compiling .pioenvs/cam/esp_https_ota/src/esp_https_ota.c.o
Compiling .pioenvs/cam/esp_https_server/src/https_server.c.o
Compiling .pioenvs/cam/esp_hw_support/cpu.c.o
Compiling .pioenvs/cam/esp_hw_support/port/esp32s3/esp_cpu_intr.c.o
Compiling .pioenvs/cam/esp_hw_support/esp_memory_utils.c.o
Compiling .pioenvs/cam/esp_hw_support/port/esp32s3/cpu_region_protect.c.o
In file included from src/esphome/components/esp32_camera/esp32_camera.cpp:4:
src/esphome/components/esp32_camera/esp32_camera.cpp: In member function 'virtual void esphome::esp32_camera::ESP32Camera::dump_config()':
src/esphome/components/esp32_camera/esp32_camera.cpp:51:52: error: 'class esphome::esp32_camera::ESP32Camera' has no member named 'internal_'; did you mean 'is_internal'?
   51 |   ESP_LOGCONFIG(TAG, "  Internal: %s", YESNO(this->internal_));
      |                                                    ^~~~~~~~~
src/esphome/core/log.h:101:101: note: in definition of macro 'esph_log_config'
  101 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                                     ^~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:51:3: note: in expansion of macro 'ESP_LOGCONFIG'
   51 |   ESP_LOGCONFIG(TAG, "  Internal: %s", YESNO(this->internal_));
      |   ^~~~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:51:40: note: in expansion of macro 'YESNO'
   51 |   ESP_LOGCONFIG(TAG, "  Internal: %s", YESNO(this->internal_));
      |                                        ^~~~~
Compiling .pioenvs/cam/esp_hw_support/esp_clk.c.o
Compiling .pioenvs/cam/esp_hw_support/clk_ctrl_os.c.o
Archiving .pioenvs/cam/esp-idf/esp_http_server/libesp_http_server.a
Compiling .pioenvs/cam/esp_hw_support/hw_random.c.o
Compiling .pioenvs/cam/esp_hw_support/intr_alloc.c.o
Archiving .pioenvs/cam/esp-idf/esp_https_server/libesp_https_server.a
Compiling .pioenvs/cam/esp_hw_support/mac_addr.c.o
Compiling .pioenvs/cam/esp_hw_support/periph_ctrl.c.o
Archiving .pioenvs/cam/esp-idf/esp_https_ota/libesp_https_ota.a
Compiling .pioenvs/cam/esp_hw_support/revision.c.o
Compiling .pioenvs/cam/esp_hw_support/rtc_module.c.o
*** [.pioenvs/cam/src/esphome/components/esp32_camera/esp32_camera.cpp.o] Error 1
========================== [FAILED] Took 2.86 seconds ==========================
```
